clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached

I'm currently testing manual install of Sprout with this, but can you review in parallel with that? Mitigates #121 for now but isn't a completely future-proof fix.
This is mostly indentation, so I recommend `?w=1`.

[Reviewer: Matt] Don't rewrite /etc/init.d/memcached if it doesn't exist yet

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Add those brackets you deleted back into the diags script so that the CURRENT_DUMP_DIR isn't changed beyond the scope of the loop
I ran bash -n over the script to check I hadn't messed up the syntax but im not intending on doing any more testing.
Thanks.

Reviewer AMC: Create dump directories correctly again

---

clearwater-snmpd/usr/share/clearwater/infrastructure/scripts/snmpd
debian/clearwater-infrastructure.init.d

Matt, please can you review this change for #127 to make sure stats work across reboots. This consists of two parts:
*  Add a section to clearwater-snmpd's infrastructure script to create the stats directory. 
*  Make sure this is run before anything that will bind to a socket in that directory. 
Tested as part of https://github.com/Metaswitch/crest/pull/187

[Reviewer: Matt] Make stats work across reboots. 

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
debian/clearwater-diags-monitor.postinst
debian/clearwater-diags-monitor.prerm

Hi Rob,
Please can you review this pull request? It contains fixes for https://github.com/Metaswitch/clearwater-infrastructure/issues/129 and https://github.com/Metaswitch/clearwater-infrastructure/issues/40.
We've discussed the three changes I've made for https://github.com/Metaswitch/clearwater-infrastructure/issues/129. They are the following - create the crash directory if we fail to cd into it because it doesn't exist, check the word core is in the supposed core file, and don't remove the tmp crash directory on upgrade.
I just changed the permissions on the files for https://github.com/Metaswitch/clearwater-infrastructure/issues/40 whilst I was making changes to the diags monitor. I'll update the doc mentioned in the issue if you're happy with it.
I've done some testing. I've checked …

[DO NOT MERGE] Reviewer RKD: Diags monitor fixes

---

clearwater-memcached/usr/share/clearwater/infrastructure/conf/memcached_11211.monit

Oh hey there Rob,
Can you review this change to our memcached monit file. In short, timing out memcached (which I think is the equivalent of unmonitoring it whatever state it's in) is just giving up and is never a good idea, so let's not do it. At the moment I think we're doing this if the poll_memcached script fails two out of three times.
I'll hold off merging until the release is cut.
Thanks,
Graeme

Reviewer RKD: Never timeout memcached

---

debian/clearwater-diags-monitor.postinst

This reverts changing the file permissions for the clearwater diags monitor as Ellis/Homer/Homestead-prov needed it. 
Linked to #40

[No reviewer] Revert file permissions

---

debian/clearwater-infrastructure.init.d

Fixes #105 . Tested:
```
[homestead-1]ubuntu@ec2-54-196-221-53:~$ sudo service clearwater-infrastructure status
clearwater-infrastructure is not a long-running daemon so does not have a 'status' command
[homestead-1]ubuntu@ec2-54-196-221-53:~$
```
(@nicolemcp, FYI.)

[Reviewer: Ellie] Sensible output from 'service clearwater-infrastructure status'

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Ellie,
Please can you review this change which fixes #96?  Basically, it waits for idle CPU to be at least 40% before starting to gather diagnostics.  If further traps are generated in the meantime, it caps their disk space at 1GB and deletes the **newer** ones (generally the earlier diagnostics are likely to be the most useful).
I've live-tested by deliberately loading the system and then triggering a sprout crash.  I've also tested filling up the diags directory and checking that additional files are deleted while CPU is high.
Thanks,
Matt

[Reviewer: Ellie] Wait for CPU usage to drop below 60% before gathering diagnostics

---

clearwater-infrastructure/usr/share/clearwater/bin/poll-tcp

Hi Andy,
Please can you review this change to poll-tcp to allow an optional IP address to be specified in the arguments?
I've tested by running it on an AIO node like so
poll-tcp 9160 (failed)
poll-tcp 9160 localhost (passed)
poll-tcp 9160 127.0.0.1 (passed)
poll-tcp 5052 (passed)
clearwater-cassandra PR to follow.
Thanks,
Graeme

Reviewer AMC: Add optional IP argument to poll-tcp

---

clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached

As it says. Needed due to these changes - https://github.com/Metaswitch/memcached/pull/2.

Reviewer AMC: Remove single quotes from memcached conf file

---

debian/control

This PR makes clearwater-memcached depend on a specific version of memcached. We discussed this and agreed it was a good idea as it prevents a new version of memcached (that is not created by us) with a higher version number from taking precedence over our version. 
Tested by running `sudo clearwater-upgrade` and checking everything upgraded correctly.

[Reviewer: Andy] Fix the version of memcached clearwater-memcached depends on

---

clearwater-socket-factory.md
clearwater-socket-factory/clearwater_socket_factory.c
debian/clearwater-socket-factory.upstart

Andy, please can you review this PR that prevents the socket factory from creating connections to arbitrary hosts. As it only needs to connect to one host at the moment, I've only enhanced it to take a single host (rather than a list). 
Tested by changing `sas_server` variable on a sprout node, restarting sprout, and checking sprout connected to the new host. 
I have also updated the socket factory readme. No other docs changes are needed.

[Reviewer: Andy] Only allow the socket factory to connect to a single specified host

---

clearwater-diags-monitor/etc/cron.d/clearwater-sysstat

Rob, please could you review this small change to:
- Send clearwater-sysstat output to /dev/null, to prevent entries like this in syslog: /var/log/syslog.1:Feb 16 06:23:01 sproutA CRON[30594]: (CRON) info (No MTA installed, discarding output)"
- Create a new file clearwater-sa at the start of each day, rather than appending to any existing one.
(same changes as before)

[Reviewer: Rob] Fix clearwater-sysstat

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/switch_to_migrated_config

If you use `source` in the shim file, then non-bash scripts can't dot in the shim file successfully.  Using `.` is more reliable.

Reviewer Rob - Use . over source to allow sub-sourcing

---

clearwater-infrastructure/usr/share/clearwater/bin/poll-sip

This change makes the SIP poll tolerances (i..e the number of seconds monit will wait for sprout to response to OPTIONs polls before it decides that sprout is unresponsive) scale linearly with the target_latency_us config parameter (if specified).
The need for this change arises when target latency is order of a second or higher.  sprout will not throttle client load until elapsed request time reaches the target latency and, assuming load remains constant, will subsequently reject commands only to keep average latency at this level (with potentially all worker threads locked up in these high letency requests).  While OPTIONs processing does not involve HSS access, an OPTIONS request received on a system in this loaded state will nevertheless be queued up behind other messages that ARE …

Reviewer AMC: Scale OPTIONS poll tolerances linearly with target latency

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/configlint.py
clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/migrate_local_config
clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/switch_to_migrated_config

This:
* moves alias_list into local config
* adds the local/remote site names to local config
* comments out any blank entries in local config (so defaulting local_site_name still works)
* doesn't migrate chronos_hostname (as the default is always right) but leaves the old value commented out
* only uses shared_config if it exists (@bossmc)

[Reviewer: Ellie] Fix up migration scripts

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Adds appropriate diags to clearwater-diags-monitor. Tested live:
```
$ head 20150521211731Z.ec2-54-90-232-39.gather_diags.temp/etcd_*
==> 20150521211731Z.ec2-54-90-232-39.gather_diags.temp/etcd_cluster_health.txt <==
cluster is healthy
member 12f0b9b6edc54780 is unhealthy
member 47064dfe798b77c4 is healthy
member 4d54105549ec3008 is healthy
member 5560d38d82aff414 is healthy
member 678eb7d71ca4a00b is healthy
member 7107133b43a34139 is healthy
member 82577902f771bc49 is healthy
member 86b40cbc7583f1c4 is healthy
==> 20150521211731Z.ec2-54-90-232-39.gather_diags.temp/etcd_datatore_clusters_health.txt <==
Describing sprout memcached cluster in site single_site:
Local node is in this cluster
Cluster is healthy and stable
10.101.154.144 is in state normal
10.73.136.148 is in state normal …
```

[Reviewer: Alex] etcd diagnostics

---

clearwater-infrastructure/usr/share/clearwater/bin/alarms.py

Tested by running this on your sprout-1 node:
```
>>> has_snmp_ip = (call('. /etc/clearwater/config; [ "x$snmp_ip" != "x" ]', shell=True) == 0)
>>> print has_snmp_ip
True
>>> has_snmp_ip = (call('. /etc/clearwater/config; [ "x$snmp_ipp" != "x" ]', shell=True) == 0)
>>> print has_snmp_ip
False
```

[Reviewer: Ellie] Improve checking for snmp_ip

---

debian/clearwater-infrastructure.postinst

As discussed, this saves the user from creating the shim file manually at install time.  This only has an effect if `etc/clearwater/config` doesn't already exist.

Reviewer Matt - Create shim file at install time if sensible

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
debian/control

Clearwater diags monitor was starting before /etc/clearwater/config was made by clearwater-infrastructure.  Fixed in two ways, one to make diags monitor depend on infra and the other to make diags monitor exit if it can't load the config (it will be restarted by monit).
Tested on a live system.

Reviewer Ellie - clearwater-diags-monitor fixes for etcd work

---

clearwater-infrastructure/usr/bin/clearwater-aio-install
debian/clearwater-auto-config-aws.init.d
debian/clearwater-auto-config-aws.install
debian/clearwater-auto-config-docker.init.d
scripts/clearwater-aio-install.sh

Matt, can you review this change to add a script for an AIO install. I've taken it from the OVF install, and I'll move both Chef and clearwater-vm-images to use this. 
I've also fixed up the aws/docker auto config packages to use local/shared config. 
Part of the fix for https://github.com/Metaswitch/chef/issues/192

[Reviewer: Matt] Add in an all-in-one install script

---

clearwater-infrastructure/usr/share/clearwater/bin/alarms.py

Same kind of problem as yesterday. I've tested by running the following in the Python interpreter:
```
>>> try:
...   int("as")
... except Exception as e:
...   import syslog
...   syslog.syslog(syslog.LOG_ERR, str(e))
```

[Reviewer: Andy] Report exceptions to syslog properly

---

debian/clearwater-auto-config-docker.init.d

Matt
I've added code to the docker auto config script to learn the DNS server address from resolv.conf so that Bono and Sprout send DNS requests to the right place.  Can you (or one of the team) review please.
Thanks, Mike

[Reviewer Matt] Learn DNS server address from resolv.conf

---

debian/clearwater-auto-config-docker.init.d
debian/clearwater-auto-config-docker.install
debian/clearwater-auto-config-generic.init.d
debian/clearwater-auto-config-generic.install

Hi Rob,
Can you review your own suggested fix to https://github.com/Metaswitch/clearwater-infrastructure/issues/82, where clearwater-auto-config-generic (and presumably clearwater-auto-config-docker) have a circular dependency with clearwater-infrastructure.
I haven't done any testing of this - do you think it's worth it, and if so, what is the easiest way to test this?
This fixes https://github.com/Metaswitch/clearwater-infrastructure/issues/82.
Thanks,
Graeme

Reviewer RKD: Auto config packages use their own bracket_ipv6_address.py scripts

---

scripts/clearwater-aio-install.sh

Matt, please can you review this change which adds `set -e` to the script that installs an AIO node. I will be testing this as part of fixing up the OVF, but this is a generally good thing to do anyway.

[Reviewer: Matt] Ensure the AIO install script uses set -e

---

scripts/clearwater-aio-install.sh

Alex,
Please can you review this fix to make AIO nodes work on Ubuntu 14.04.  It seems like the memory requirements on 14.04 are higher, and so the OOM killer is hot more frequently.  To avoid this, my fix is to reduce Cassandra's memory requirements from half of all memory to approximately a third.  Given that we don't expect AIO nodes to run under much load, this should be fine.
I've tested live.
Matt

[Reviewer: Alex] Reduce Cassandra memory usage on AIO nodes

---

debian/clearwater-memcached.postinst

Fixes #175. This is safe because /usr/share/clearwater/infrastructure/scripts/memcached stops memcached if it changes something (https://github.com/Metaswitch/clearwater-infrastructure/blob/master/clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached#L104).

[Reviewer: Matt] Don't stop memcached unnecessarily

---

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
debian/clearwater-snmpd.postinst

I spotted that SNMP stats weren't working on staging - this is because /var/agentx defaults to permissions 0700, and SNMPD doesn't change the permissions even if you subsequently change the config. This adds a chmod to fix that up. (I think this is a 14.04 change in behaviour, though maybe I'm just really bad at testing).
Tested live (by upgrading clearwater-snmpd on my Bono and confirming that it worked).

[Reviewer: Ellie] Fix up permissions on /var/agentx directory

---

debian/clearwater-snmpd.postinst

Should fix clearwater-docker. (Actually, I think this would have been a potential bug on all initial installs.)

[Reviewer: Graeme] Only change /var/agentx permissions if it already exists

---

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
clearwater-snmpd/usr/share/clearwater/infrastructure/scripts/snmpd

Now that alarms live in a standalone process (https://github.com/Metaswitch/clearwater-snmp-handlers/blob/master/debian/clearwater-snmp-alarm-agent.init.d#L106), we don't need to update snmpd.conf with the alarm destinations - they're passed into the standalone process directly.
Fixes #186, supersedes #196.

[Reviewer: Matt] Remove fragile SNMP alarm parsing code

---

debian/clearwater-infrastructure.init.d

This fix means that only files in the scripts folder get run

[Reviewer: Graeme] Only run the scripts in the scripts folder

---

clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached
debian/clearwater-memcached.prerm
debian/control

Corresponding fix to https://github.com/Metaswitch/memcached/pull/13.
Note that I'm echoing into /etc/default/memcached rather than creating `clearwater-memcached/etc/default/memcached` - this is because I'm nervous about file conflicts (if clearwater-memcached and a pre-upgrade memcached are both briefly trying to manage /etc/default/memcached). I'm not quite sure what the upgrade ordering is, so I might be being over-cautious, but it can't hurt.

[Reviewer: Andy] Move /etc/default/memcached responsibility into clearwater-memcached

---

clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_plugin.py
clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_remote_plugin.py
clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_utils.py
debian/clearwater-memcached.postinst
debian/clearwater-memcached.prerm

Move Memcached plugin to Memcached (no changes to plugin code) and update debian files. Update the reload_memcached_users script to reload all processes that have indicated an interest in memcached.

[Reviewer: Andy] Move memcached plugin to memcached

---

debian/control

Add clearwater-infrastructure as a dependency. 
I've spun up a clearwater-base box through chef and checked nothing obviously broke
Fixes #260

[Reviewer: Andy] Add clearwater-infrastructure dependency

---

debian/clearwater-socket-factory.upstart

Adding a short sleep to avoid hitting race condition between socket-factory and shared_config being applied.
Should prevent upstart spamming respawn, and then giving up before the race condition closes.
Fixes #266

Add sleep to clearwater-socket-factory.upstart

---

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd

This avoids the problem in https://github.com/Metaswitch/clearwater-infrastructure/issues/261. Unlike https://github.com/Metaswitch/clearwater-net-snmp/pull/2, it's a workaround rather than a fix - but if you think that PR's ramifications are too risky/too poorly understood, this is a workable alternative.

[Reviewer: Andy] Make the sysDescr OID visible to the 'clearwater' community

---

clearwater-infrastructure/usr/share/clearwater/bin/generic_create_diameterconf

Accompanying change for https://github.com/Metaswitch/freeDiameter/pull/27/.
I'm not intending to abstract it any further, but if we ever wanted to it would presumably be trivial to do so.

Reviewer AMC: Ignore custom mandatory AVPs from Metaswitch

---

clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_utils.py

Please can you review this change to correctly fill in the memcached cluster_settings file on an IPv6 system. I've tested this by setting up both v4 and v6 systems, and checking the files was correctly formatted in both cases.

[Reviewer: Ellie] Cope with ipv6 when setting up cluster_settings

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/hostname

This fixes #67 (with the approach discussed in that issue).
I've tested by editing my Chef cookbook to make public_hostname in local_config always be `hghdsghsaghjdsgdhjjw.gfshjgsdfxdsgjsagsaj`, spinning up a deployment, and checking my Sprout ad Homestead nodes (specifically checking Sprout, Cassandra and sudo as the three troublesome commands described in #67):
```
[homestead-1]ubuntu@hghdsghsaghjdsgdhjjw:~$ sudo ls
[homestead-1]ubuntu@hghdsghsaghjdsgdhjjw:~$ hostname
hghdsghsaghjdsgdhjjw
[homestead-1]ubuntu@hghdsghsaghjdsgdhjjw:~$ ps aux | grep cassandra
cassand+ 24326  2.6 66.8 1726196 1368572 ?     SLl  22:00   0:12 /usr/lib/jvm/java-7-openjdk-amd64//bin/java -ea -javaagent:/usr/share/cassandra/lib/jamm-0.2.5.jar -XX:+CMSClassUnloadingEnabled -XX:+UseThreadPriorities …
```

[Reviewer: Matt] Ensure that local and public hostnames always resolve

---

clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_plugin.py

Looks like I missed this one too.
Use alarm_manager from python-common.

[Reviewer Ellie] Update memcached plugin to use new alarm infrastructure.

---

clearwater-infrastructure/usr/share/clearwater/bin/check-uptime
clearwater-memcached/usr/share/clearwater/infrastructure/conf/memcached_11211.monit

This fixes around issue #293. Rather than allowing monit to exec the issue_alarm script (which triggers it to mark the script as failed), get our check-uptime script to clear the alarm.
I've marked all of the other repos that I've fixed this in as no-reviewer as it's all the same stuff.
I've checked that this fixes the issue by spinning up a deployment and running `watch sudo monit summary`.

[Reviewer: Ellie] Uptime failure

---

clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_plugin.py

As with the chronos plugin changes linked below, this should avoid alarm flicker by stopping on_stable_cluster calling into on_cluster_changing to write cluster settings.

[Reviewer: Rob] Separate out write_cluster_settings function

---

clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_remote_plugin.py

Same changes as in https://github.com/Metaswitch/clearwater-infrastructure/pull/300
This doesn't change any functionality, but it keeps the two plugins in line so as to avoid future confusion

[Reviewer: Rob] Make remote memcached plugin match standard plugin

---

clearwater-memcached/usr/share/clearwater/infrastructure/conf/memcached_11211.monit
clearwater-memcached/usr/share/clearwater/infrastructure/scripts/check-memcached-uptime

Monit can't pass arguments to check-program scripts in its current version.
This should fix the "failed" flickering issue.
I've raised a bunch of other similar pull requests - no need to review them all.

[Reviewer: Ellie] Cope with Monit restrictions

---

clearwater-auto-config/etc/clearwater/local_config
debian/clearwater-auto-config-aws.init.d
debian/clearwater-auto-config-generic.init.d
scripts/clearwater-aio-install.sh

This installs the clearwater-management package (config/cluster/queue manager) on all-in-one nodes. I've tested live (by spinning up an AWS AIO node and running some live tests).

[Reviewer: Adam] Install etcd on all-in-one nodes

---

clearwater-infrastructure/usr/share/clearwater/bin/sync_alarms.py

Counterpart to https://github.com/Metaswitch/clearwater-snmp-handlers/pull/135

[Reviewer: Chris] Remove deprecated option from sync_alarms.py

---

debian/clearwater-auto-config-aws.init.d
debian/clearwater-auto-config-docker.init.d
debian/clearwater-auto-config-generic.init.d

We saw an issue where the new entries in /etc/hosts weren't being picked up on AIO nodes. This should fix that issue.
I'm testing by spinning up an AIO node with this change right now.

Reviewer EM: Restart dnsmasq

---

rpm/clearwater-memcached.spec
rpm/clearwater-snmpd.spec

Small changes to do the following for Centos builds:
- Fix package dependencies for clearwater-snmp
- Fix version formatting for dependencies in clearwater-memcached (the only other build that depends on a specific package version)
- Start snmp on installation of clearwater-snmpd

[Reviewer: Matt] Fix package version dependencies, and start snmp on install

---

clearwater-radius-auth/etc/libnss-ato.conf
clearwater-radius-auth/usr/share/clearwater/infrastructure/install/clearwater-radius-auth.postinst
clearwater-radius-auth/usr/share/clearwater/infrastructure/install/clearwater-radius-auth.prerm
rpm/clearwater-radius-auth.spec

Tested by:
* installing it and checking I could SSH in with my RADIUS credentials, and that I became the right user
* checking that I couldn't log in with an incorrect username or password
* upgrading and checking that I didn't get multiple entries in /etc/pam.d/sshd or /etc/nsswitch.conf
* uninstalling and checking that the entries added were removed
All that was on CentOS - I'll also test the first bullet (is it basically working) on Ubuntu.

[Reviewer: Adam] Get clearwater-radius-auth working under CentOS

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/install/clearwater-infrastructure.postinst

The file `/etc/bash.bashrc` does not exist on centos so we shouldn't try to edit it. 
This caused the script to bail out early which causes various carnage (`/etc/clearwater/config` file not added, certain eggs not installed, etc). 
Tested by installing clearwater-infratructure on a vanilla centos box, checking the out put was clean and that `/etc/clearwater/config` was created.

[Reviewer: Ellie] Don't attempt to edit /etc/bash.bashrc if it does not exist

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/install/clearwater-infrastructure.prerm

Follow on from https://github.com/Metaswitch/clearwater-infrastructure/pull/340 - use the same fix in the prerm script. 
Tested by removing clearwater-infrastructure and checking there were no errors reported by yum.

[Reviewer: Ellie] Done try to remove a section from a non-existent file. 

---

debian/clearwater-diags-monitor.init.d
debian/clearwater-infrastructure.init.d
debian/clearwater-secure-connections.init.d

Matt, please could you review this PR to make some scripts in clearwater-infrastructure use the new `init-utils.bash` script I added recently.
I've tested this by installing clearwater-infrastructure and clearwater-diags-monitor on a node. Then:
* `sudo service clearwater-infrastructure restart` ran cleanly. 
* `sudo service clearwater-diags-monitor start` ran cleanly and caused the diags monitor to start.
* `sudo service clearwater-diags-monitor stop` ran cleanly and caused the diags monitor to stop.
I've not tested clearwater-secure-connections as the change is identical to the change for clearwater infrastructure.

[Reviewer: Matt] Migrate init.d scripts to use init-utils.bash where appropriate

---

rpm/clearwater-snmpd.spec

Net-snmp-utils was not explicitly required by clearwater-snmpd. 
This meant that installing clearwater-snmpd did not install commands such as `snmpget`.
Tested on a clean centos node, all works fine

[No Reviewer] Fix spec to pull in net-snmp-utils

---

clearwater-infrastructure/usr/bin/clearwater-upgrade

Hi Matt, 
Please can you review this PR that enhances `clearwater-upgrade` top upgrade all repos whose name starts with "clearwater" (rather than just the single repo whose name is exactly clearwater). This is useful if you want to serve up code from multiple repos (e.g. from the public repo, and a private repo). 
Tested live.

[Reviewer: Matt] Upgrade all repos starting with the word clearwater.

---

debian/clearwater-diags-monitor.init.d

Was seeing the behaviour that clearwater-diags-monitor process was not being restarted correctly, as there was a PID file with a process number in, but that number did not correspond to any running process. 
The updated logic below is the fix for this. 
Can you just check this is the right thing here, and i'm not missing something obvious?

[Reviewer: Ellie] Update checkpid logic

---

src/issue-alarm.cpp

Matt, this PR changes the issue-alarm script to always return success. This matches the previous python script.
Tested by checking that the issue alarm script succeeded (but still logged the errors) when the alarms agent wasn't installed

[Reviewer: Matt] Make issue alarm always succeed

---

rpm/clearwater-infrastructure.spec

Simply adds ntp as a dependency in rpm spec file to mirror debian control.
Trying to upgrade a clearwater-infrastructure installation to the new package using `yum update`, on a node that doesn't have ntp already installed, will throw a dependency error. This can be resolved by using `yum install` or just installing ntp before upgrading. 
Tested, and this does correctly install ntp. Tested that monit brings ntp back when killed, and it does. 
This installation does not enable the ntp service in systemctl, but as monit will be in place I do not think this is an issue.

[Reviewer: Ellie] Add ntp to infrastructure dependencies

---

scripts/clearwater-aio-install.sh

I've been thinking about how to do more testing of the release before actually publishing packages to our stable repo. I think the right approach for the OVA is:
* freeze code
* install the packages from staging
* verify that the OVA works
* set it up so that future updates come from the stable repo
This PR accomplishes that goal by allowing you to specify a different repo to use after the initial install. I'll then make the corresponding changes to https://github.com/Metaswitch/chef/blob/35e37eeacdd55aa2926301b30c3ad09789555e0f/cookbooks/clearwater/recipes/cw_aio.rb#L39 and https://github.com/Metaswitch/clearwater-vm-images/blob/36cf7806c063889cf68cf12b233421bea2bb6d9b/ubuntu-ovf/ubuntu-server.seed#L106 without review.
One thing I wasn't sure on was whether I should add updates_repo as …

[Reviewer: Matt] Allow using a different repo for initial installs and upgrades

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/logging.bash

As part of #334, I introduced a bug when the logging library is sourced from an environment with 'set -e' which causes the script to terminate on log calls.
This fix reverts the broken change made in that PR.
No reviewer as this reverts the code to a state already approved in the above PR.

[No Reviewer] Fix error when -e is set

---

debian/control

As I've seen diag dumps that include
```
/usr/share/clearwater/bin/clearwater_diags_monitor: line 731: gzip: command not found
```

[No reviewer] Make sure gzip is installed

---

debian/clearwater-auto-config-generic.init.d

Fixes #363.  Tested live by patching AIO instance and rebooting.

[Reviewer: Rob] Change hostname from cwaio to cw-aio

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/1hosts

Add `::1 localhost` to `/etc/hosts` so that we can return a lookup for `localhost` in IPv6 only networks.
This fixes Metaswitch/sprout#1510 and gets us further towards fixing Metaswitch/homestead#13

[Reviewer: RKD] Add IPv6 localhost entry to /etc/hosts

---

clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location
clearwater-diags-monitor/usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.postinst

This script triggers diags collection, then blocks until the diags completion is complete. Output looks like:
```
Starting diagnostics collection.
Collecting diagnostics.....................
Diagnostics have been collected at /var/clearwater-diags-monitor/dumps/20161004101343Z.ip-10-0-88-92.gather_diags.tar.gz
```
Tested live

[Reviewer: Adam] Add gather diags script that blocks until completion

---

clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location

This is better than hardcoding either 'clearwater' or 'ubuntu' (or indeed 'centos' or 'defcraft').

[Reviewer: Ellie] Use $HOME to determine the dump directory

---

clearwater-infrastructure/usr/bin/clearwater-upgrade
clearwater-infrastructure/usr/share/clearwater/utils/check-root-permissions

This fixes the desire raised in https://github.com/Metaswitch/clearwater-etcd-plugins/issues/9 to have a common method of checking for root permissions.
Usage as documented is:
```bash
. /usr/share/clearwater/utils/check-root-permissions [exit_code]
```
I've tested clearwater-upgrade live on a sprout node to check that this works.

[Reviewer: Ellie] Add script to check for root permissions

---

clearwater-infrastructure/usr/share/clearwater/bin/poll-http

https://github.com/Metaswitch/sprout/issues/1570 saw poll_sprout_http failing fairly often, causing monit to kill the sprout process.
Chronos was also seen to be being repeatedly killed in GVD testing.
Tracing it back, we found that if we are overloaded in https://github.com/Metaswitch/cpp-common/blob/54371f20e89c60a04218bdeebe90d687f26345fc/src/httpstack.cpp#L313  we will return a 503 response with no body, where the 'ping' poll would normally return a 200 with "OK" in the body.
In https://github.com/Metaswitch/clearwater-infrastructure/blob/master/clearwater-infrastructure/usr/share/clearwater/bin/poll-sip#L77 , the poll-sip script already checks for either a 200 or a 503 response, as the intent of the poll scripts is to check for liveness/responsiveness, not whether we are overloaded. …

[reviewer: Ellie] Poll http passes on 503 as well as 200 OK responses

---

clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location

Ellie,
This resolves a bug you saw when we weren't dumping diags to the correct location.
If we don't have $HOME defined when this script is invoked, we should still place the diags in the correct location. As such, we have a search list of places we look for to work out where to place the diagnostics bundle.
I've tested live on a Project Clearwater system spun up on EC2

[Reviewer: Ellie] Use a sensible location when invoked with a HOME dir

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/hostname

Fixes https://github.com/Metaswitch/clearwater-monit/issues/44
Check that the shell commands succeed when trying to change the hostname.

[Reviewer: Ellie] Check commands succeed when changing hostname

---

clearwater-infrastructure/usr/share/clearwater/bin/run-in-signaling-namespace

Adds permissions check to the run-in-signaling-namespace check. Tested live.

[Reviewer: Graeme] Enforce that run-in-signaling-namespace is run with sudo permissions

---

clearwater-infrastructure/usr/share/clearwater/bin/poll-sip

For issue https://github.com/Metaswitch/sprout/issues/1626
This is not the full fix! 
This is just to unblock further perf-testing in the test team.

[No reviewer] Temporary workaround for poll-sip issue

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Adam,
Please can you review this fix to #424?  Basically, the `$(...)` was in the wrong place after our CentOS porting work.  I've tested live.
Since I noticed it, I've also fixed up our ifconfig logging so that we don't overwrite the no-namespaced file with the namespaced one.
Thanks,
Matt

[Reviewer: Adam] Fix get_cw_package_config_files

---

rpm/clearwater-radius-auth.spec

Caught this doing some manual testing building some images.
yum reported an error running the postinst script. This is because the script no longer exists.
Should have been included in #410 but was missed. 
Tested building the RPM and installing on a CentOS machine.

[No reviewer] Remove calls to non-existent scripts

---

clearwater-auto-config/etc/clearwater/shared_config
debian/clearwater-auto-config-aws.init.d
debian/clearwater-auto-config-docker.init.d
debian/clearwater-auto-config-generic.init.d

As mentioned in my comments on your PR, we need to add ralf_session_store to the docker autoconfig, and we need to then mirror the changes that we made to the docker autoconfig to the aws and generic ones too.
(Note that generic and aws don't have Ralf, so I haven't added the ralf_session_store to those).
I've created an AIO node and run the live tests against it to verify this.
I've set this as a PR into your branch as it's based off the changes you made.

[Reviewer: MGM] Fix up autoconfig

---

clearwater-memcached/usr/share/clearwater/infrastructure/install/clearwater-memcached.postinst

This matches what we do elsewhere, and resolves config resolution at
installation time.
This matches the change made in https://github.com/Metaswitch/astaire/pull/85

[Reviewer: Seb] Run script by restarting clearwater-infrastructure

---

debian/clearwater-auto-config-docker.init.d

Kubernetes services are always exposed in DNS as `<service name>.<domain>` and `<service name>` cannot contain periods.   This means that Sprout cannot be accessed via icscf.sprout and scscf.sprout.   As a workaround we configure icscf_uri and scscf_uri to be just sprout with explicit ports.   This also works fine when deploying on vanilla Docker with e.g. Docker compose.

Support Clearwater running on Kubernetes

---

clearwater-infrastructure/etc/bash.bashrc.clearwater

Seb,
This updates the prompt to match the expected packages for both split storage and pre-split storage.
I've tested on staging sprout, ralf and homestead nodes, and split storage vellum nodes.

[Reviewer: Seb] Update prompt for split storage

---

debian/rules

This was present in palaven, but was missed when we originally moved the vellum and dime packages to be built here.

[No reviewer] Add dh_strip for vellum and dime

---

debian/clearwater-auto-config-aws.init.d
debian/clearwater-auto-config-generic.init.d

We discussed this fix last week. I have built an AMI from this code, and tested. All services report they are working, and etcd clusters fine.

[Reviewer: Ellie] Remove etcd data on reboots, so that saved images can boot with new IPs

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Tested by manually collecting diags on a node. My etcd_cluster_health.txt looked like this.
```
member 62b523771e44470f is healthy: got healthy result from http://10.0.166.75:4000
cluster is healthy
When the cluster was last healthy, the members were 10.0.166.75,
```

[Reviewer: EM] Add last healthy etcd cluster members to diags bundle

---

clearwater-infrastructure/etc/bash.bashrc.clearwater

Seb,
If you only install certain components of Sprout (e.g. the I-CSCF and the S-CSCF), we won't detect the node as being sprout.
Instead, check for sprout-base.

[Reviewer: Seb] Use sprout-base to identify sprout

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Seb,
It'd be useful to have the actual size of the hard disk and the partitions that it's running on to ensure that the VM was setup correctly when Clearwater was installed.
This should give us output along the lines of:
```
Disk /dev/sda: 21.5 GB, 21474836480 bytes
255 heads, 63 sectors/track, 2610 cylinders, total 41943040 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000
```

[Reviewer: Seb] Include hard disk size in diags

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

This PR changes the diags monitor to check whether the database is installed when deciding whether to collect diags, not whether the user of the database is installed.
(A better fix would be to move this into the database repo itself (e.g. https://github.com/Metaswitch/chronos/blob/dev/chronos.root/usr/share/clearwater/clearwater-diags-monitor/scripts/chronos_diags), but I'm not going to do that here - this PR covers fixing up the immediate problem)

[Reviewer: Seb] Check for the database, not for the user of the database

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Hi Chris, this PR is fixing https://github.com/Metaswitch/stats-engine/issues/473, i.e. it includes further diags for Centos in the diagnostics package. Until now we didn't have any checksum diags for Centos, which we now get (plus further diags) as a file `rpm_verification.txt` in the diags bundle. I have live tested my fix and got this output in `rpm_verification.txt` (which shows me that my manipulated file actually doesn't have a matching checksum :-) ):
```
S.5....T.    /usr/share/clearwater/bin/clearwater_diags_monitor
.......T.    /usr/share/clearwater/bin/gather_diags
.M.......  c /etc/monit/monitrc
.M.......    /usr/share/clearwater/stats-engine/fv/Gemfile
.M.......    /usr/share/clearwater/stats-engine/fv/Gemfile.lock
.M....... …
```

Collect checksum diags for RPMs on Centos

---

clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location

Hi Rob, this PR is fixing https://github.com/Metaswitch/stats-engine/issues/668: The output of `gather_diags_and_report_location` used to look like this:
```
[mvse]defcraft@localhost:~$ sudo /usr/share/clearwater/bin/gather_diags_and_report_location
Collecting diagnostics from the system.\n
This operation can take a few minutes to run.
.......................\nDiagnostics collected. These are available at /root/ftp/dumps/20170606155847Z.BEN-MVSE.gather_diags.tar.gz
```
This pull request fixes up the output:
```
[defcraft@md6-08-07-17 ~]$ sudo /usr/share/clearwater/bin/gather_diags_and_report_location
Collecting diagnostics from the system.
This operation can take a few minutes to run.
.................
Diagnostics collected. These are available at …
```

Fix up output and sudo location of gather_diags_and_report_location

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/install/clearwater-infrastructure.postinst

Seb,
Currently the check for whether /etc/skel exists is incorrect - and thus we don't add the bashrc change to new users.

[Reviewer: Seb] Fix check for presence of /etc/skel

---

clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location

There's a rogue -e in the gather_diags output that's coming from https://github.com/Metaswitch/clearwater-infrastructure/blob/master/clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location#L69.
Putting -e in echo should mean that it's able to turn \n into newline characters (http://manpages.ubuntu.com/manpages/trusty/man1/echo.1.html). 
We're using the wrong shell though; this PR fixes that.
Tested live on ubuntu/centos

Change file type

---

debian/clearwater-infrastructure.init.d

On servers using systemd as their init system, systemd generates unit
information for legacy sysvinit-style scripts based on the LSB headers
in the scripts. It uses the dependencies in the scripts to ensure that
legacy services are started at the right point.
If clearwater-infrastructure is used without clearwater-startup, on a
system using cloud-init then it's important that clearwater-infrastructure is
started after cloud-init has finished, so that cloud-init doesn't
overwrite the configuration set up by clearwater-infrastructure, in
particular the hostname of the system as defined by the field
`public_hostname` in /etc/clearwater/local_config.
Adding this header should not affect systems running upstart as an init
system (e.g. Ubuntu 14.04), because upstart uses the runlevel to
trigger …

Force clearwater-infrastructure to run after cloud-init.

---

clearwater-radius-auth/usr/share/clearwater-infrastructure/scripts/clearwater-radius-auth

This PR changes clearwater-radius-auth so that RADIUS is automatically enabled/disabled depending on whether there is any RADIUS config present. I've tested the regex works on a real file, but that's it for testing so far.

Automatically enable/disable RADIUS

---

clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location

Seb,
This resolves an issue whereby if SUDO_USER and HOME is not defined, then the diags will be dumped to an incorrect place.
This is because the "! -z" check was changed "-n" in https://github.com/Metaswitch/clearwater-infrastructure/pull/458
However, these two checks are not identical when checking whether is a string is empty if the string isn't quoted - see the warning on http://tldp.org/LDP/abs/html/comparison-ops.html and the difference between 5a and 3b in the comparison table given by https://stackoverflow.com/a/3870055.
In short
- `[ -n ]` passes (which is what the current code evaluates to
- `[ ! -z ]` fails,
- `[ -n "" ]` fails
- `[ ! -z "" ]` fails.
This is resolved by quoting the string.

[Reviewer: Seb] Quote bash variables so that -n evaluates correctly

---

clearwater-infrastructure/usr/share/clearwater/bin/generic_create_diameterconf

@eleanor-merry, I've assigned you as the suggested reviewer by Github - if you're not the right person, please let me know.
This adds a line to our freeDiameter config to disable SSL 3.0. This mitigates the susceptibility to the POODLE security vulnerability. I have confirmed that this works as intended by:
* Pasting the below change into the `/usr/share/clearwater/bin/generic_create_diameterconf` file on a Dime node;
* Rebooting the Dime node, refreshing the diameter config for all applicable services;
* Running nmap against the node for ports 5658 (homestead) and 5659 (ralf).
Before applying the fix, nmap flagged the above ports; afterwards, it comes up clean. I have also run the live tests to check that function is not impacted.

[Reviewer: EM] Disable SSL 3.0 in freeDiameter config

---

clearwater-memcached/etc/clearwater/secure-connections/memcached.conf
clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached

@AlexHockey, I've assigned to you as the listed memcached expert - please let me know if you're not the right person to take this.
We only contact memcached over TCP, so we don't need it to be listening on UDP ports. By adding `-U 0` to the configuration file, memcached won't listen on any UDP ports.
Due to this change, we don't need to secure any of the UDP traffic in 11211, so I've also removed those rules.

[Reviewer: AJH] Disable memcached listening on UDP

---

clearwater-auto-config/etc/clearwater/shared_config
clearwater-auto-config/usr/share/clearwater-auto-config/bin/init-functions
debian/clearwater-auto-config-aws.init.d
debian/clearwater-auto-config-aws.install
debian/clearwater-auto-config-docker.init.d
debian/clearwater-auto-config-generic.init.d
debian/clearwater-auto-config-generic.install

Ellie,
https://github.com/Metaswitch/sprout/pull/1872 breaks the AIO node, because we don't assume they have SRV records.
This adds the URIs (S-CSCF, I-CSCF and BGCF) to allow the AIO nodes to work again.
I've commonalized a bunch of the duplicated logic between -generic and -aws. 
Thoughts?

[Reviewer: Ellie] Update AIO nodes to not require SRV records

---

clearwater-diags-monitor/etc/cron.d/clearwater-iotop
clearwater-diags-monitor/etc/logrotate.d/clearwater-iotop
debian/control

This collects iotop stats every minute, which is useful for debugging etcd issues. 
The existing diags monitor code ensures that these are in any diags dumps.

[Reviewer: Sathiyan] Add iotop stats collections

---

clearwater-auto-config/usr/share/clearwater-auto-config/bin/init-functions

We have a `;` in the contents of the variable so we need to quote it.
Sigh.
Follow on from https://github.com/Metaswitch/clearwater-infrastructure/pull/474

[No reviewer] Quote bash variables properly

---

clearwater-auto-config/usr/share/clearwater-auto-config/bin/init-functions

Ellie,
While testing the changes in https://github.com/Metaswitch/clearwater-infrastructure/pull/288, I spotted that the I-CSCF and BGCF sproutlets don't resolve on the AIO nodes.
This is because we only add mappings for the S-CSCF.
This adds mappings for the others. I've tested on a AIO node spun up in Amazon using Chef.

[Reviewer: Ellie] Add mappings for I-CSCF and BGCF hostnames as well

---

clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached

Uncomments the -r option which allows memcached to dump a core file. I've tested that the sed command modifies the config file in the right way, and that with this option set, memcached can generate a core file when it crashes.

[Reviewer: EM] Allow memcached to dump a core file

---

clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached

This increases the memory limit for memcached when Cassandra isn't in use.

[Reviewer: Seb] Increase memory limit for Memcached

---

clearwater-auto-config/etc/clearwater/shared_config
clearwater-auto-config/usr/share/clearwater-auto-config/bin/init-functions
debian/clearwater-auto-config-docker.init.d

Configure `homestead_impu_store` alongside `sprout_registration_store`.

[Reviewer: Adam] Configure Homestead IMPU Stores in auto config

---

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd

_As discussed_
Use `127.0.0.1` not `localhost` for proxying snmp requests.
If the hostname you're proxying to isn't resolvable at the point snmpd is restarted, the proxying will not work at all, even if the hostname later becomes resolvable.
By using `127.0.0.1` we avoid this.
This is a fix for https://github.com/Metaswitch/clearwater-issues/issues/2406
I've manually tested that this fixes the issue by:
1. making `localhost` unresolvable
2. restarting snmpd
3. making `localhost` resolvable again
4. Attempting to query one of the proxies OIDs: .1.2.826.0.1.1578918.9.10.9.1.2.1, which worked (it didn't before this fix)

[Reviewer: Richard] Use 127.0.0.1 not locahost for proxying requests

---

clearwater-infrastructure/usr/share/clearwater/utils/cassandra_enabled
clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached

This adds a common mechanism for allowing packages to enable Cassandra.
Each script in `/usr/share/clearwater/cassandra/users/` can set `USE_CASSANDRA` to `Y` to enable Cassandra. If it does (either based on config, or just always), then Cassandra will be started - as per the related Cassandra change.

[Reviewer: Adam] Common script for enabling cassandra

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/1hosts

Seb,
There's a bug in the `1hosts` script.
Each `clearwater-infrastructure` is restarted, if the node has a local IPv6 address, we will add a mapping to /etc/hosts.
This is because there is no space between the end of address, and the ipv6.arpa address - e.g.
```
fd5f:5d21:845:1422:1::45d 45d.0.0.1.1422.845.5d21.fd5f.ip6.arpa # added by clearwater-infrastructure 1hosts script
```
I've fixed by not checking for a space as part of the grep (so we clean up old entries), and adding a space to the IPv6 entry (to match the others).
I've tested this live on a system and verified it resolves a problem.

[Reviewer: Seb] Don't create duplicate IPv6 mapping addresses

---

clearwater-diags-monitor/etc/cron.d/clearwater-sysstat

Hi Krista
Can you review this infrastructure change for me?  The problem I'm fixing is that, on systems that have been deployed for more than a month, the sadc (system diagnostic) output that is written to "/var/log/sysstat/clearwater-sa<day of the month>`" gets appended to the end of the file that was created a month previously.  In other words, the "-F" parameter that Nicole added in https://github.com/Metaswitch/clearwater-infrastructure/pull/162 doesn't seem to have had the intended effect, which was to truncate the sa file and start again (otherwise you get spurious averages in analyses of the sa files that include data form the previous month, and, perhaps more ominously we leak 3MB of diskspace a day)
I've therefore added an explicit delete of the file with the day number at 00:00. …

[Reviewer KH1] Delete the sa file from last month, if any

---

clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached

Seb,
To the extent I can test this fix, I think this works.
This changes memcached's default behaviour so that it doesn't evict data if the cache is full, and instead will return an error to the write.

[Reviewer: Seb] Return errors if memcached is full

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

This is a fix for: https://github.com/Metaswitch/clearwater-issues/issues/2383
Creating a diags bundle may fail if we run out of disk space. Since we move any core files into a temporary directory then delete the directory when we're done, if we fail to create the diags bundle we lose the core file.
This fixes the issue by checking whether we succeeded in creating the diags archive. If not, we:
- delete everything in the temporary directory that isn't the core file
- this is because the most common cause of failing to create the bundle will be disk space issues, and the core file is the most important file which doesn't exist anywhere else (log files and config files all exist elsewhere). By deleting everything else, we make sure we're not taking up more disk space than the core file …

[Reviewer: Richard] Don't delete core file if creating the diags bundle fails

---

clearwater-diags-monitor/etc/clearwater/diags-monitor/core_pattern
clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
clearwater-diags-monitor/usr/share/clearwater/bin/compress_core_file
clearwater-diags-monitor/usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.postinst

Core files can be large, and we don't necessarily have much disk space. So this changes our core file pattern to pipe the core file to a script which uses `gzip` to compress them to disk.
(The compression is done by a separate file rather than inline in the core pattern because you pass a program to a core pattern, not a shell command, and we want to use a shell to redirect the gzip output to a file)
I've removed the (now unnecessary) compression of core files in the diags bundle, as they're compressed already.
I've also added a `service clearwater-diags-monitor stop` to the postinst script so that we'll pick up the new core file pattern when the new package is installed.
I've live tested this by sending SIGABRT to sprout and homestead and verifying that the core files are compressed when …

[Reviever: Richard] Compress core files as we write them to disk

---

clearwater-infrastructure/usr/share/clearwater/bin/generic_create_diameterconf

Modifies the script used to generate freeDiameter config files to accept an additional parameter - the delay between watchdog messages in seconds. This time must be at least six seconds; the script verifies that this condition is satisfied.
The script has undergone very basic live testing, with more to come.

[Reviewer: AJH] Add TwTimer parameter to Diameter config creation script

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/config_validation/project_clearwater_options.py
cw_infrastructure/cw_infrastructure/check_config_utilities.py
cw_infrastructure/cw_infrastructure/validators.py

Seb,
I've tested this on the QA system.
There's bunch of problems but the net result is that checking DNS records while using split namespaces is broken.
The main reason is because we passed in `signaling_dns_server` directly, which could be a list of IP addresses instead of a single IP address, which would cause DNS resolution to fail.
That's also some other bugs, detailed in the commit messages.

[Reviewer: Seb] Fix split DNS signaling configuration checking 

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/set_log_level
clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/set_snmp_community

As discussed elsewhere:
"Code looks good.
I was expecting the log level script to just take a number, but this is probably actually more helpful for a user setting the log level (I'm assuming that these are the only 2 log levels that we tell people to use in the manuals)."
For the record, the only guidance for log_level is for debug. It doesn't even tell you how to undo the change (although I think that's implicitly, remove the line you added).

[Reviewer: Seb] Add scripts that allow log level and snmp community names to be changed.

---

clearwater-infrastructure/usr/share/clearwater/bin/generic_create_diameterconf

SCTP support isn't currently tested / supported (and we possible may not even try to establish them if we do SRV lookups?).   But, having SCTP support enabled in FreeDiameter means that Homestead won't run at all on platforms where SCTP isn't available.  Like GKE for example.   So disable it.

Disable SCTP

---

clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config

Seb,
Previous versions of `clearwater-check-config` have allowed a `--show` option which allows the current config to be shown.
This function is now implemented by `clearwater-show-config`, but we should preserve the command line argument.
`"${@:2}"` passes any remaining arguments to the new process in the correct fashion (including handling arguments with spaces in them, somewhat surprisingly).

[Reviewer: Seb] Preserve clearwater-check-config --show

---

clearwater-infrastructure/usr/share/clearwater/infrastructure/bin/set_snmp_community

Can you review please - I've run a bunch of tests with different IP addresses to confirm it works. I also ran with a variety of bad community names and confirmed that swapping community names worked properly
Tested:
(valid connections)
cw-set_snmp_community clearwater-test 172.18.112.60 (i.e. exact address)
cw-set_snmp_community clearwater-test 172.18.112.60/32 (i.e. exact address with irrelevant subnet)
cw-set_snmp_community clearwater-test 172.18.112.60/255.255.255.255 (i.e. exact address with irrelevant subnet)
cw-set_snmp_community clearwater-test 172.18.112.60/255.255.255.252 (i.e. 60->63)
cw-set_snmp_community clearwater-test 172.18.112.60/30 (i.e. 60->63)
cw-set_snmp_community clearwater-test 172.18.112.56/29 (i.e. 56->63)
cw-set_snmp_community clearwater-test 0.0.0.0/0 (i.e. …

[Reviewer: RobD] Fix the set_snmp_community command

---

clearwater-infrastructure/usr/share/clearwater/bin/alarms.py

We use `zmq.Context.instance()` to get a 0MQ context, but this isn't safe for multithreading - two threads could use it at the same time and (possibly worse), one could terminate it while the other is using it.
@eleanor-merry, please can you review?
I've live-tested with the following stress script:
```python
import imp
from threading import Thread
from time import sleep
def foo(ii):
for jj in range(0, 100000):
kk = jj * 2
file, pathname, description = imp.find_module("alarms", ["/usr/share/clearwater/bin"])
mod = imp.load_module("alarms", file, pathname, description)
sendrequest = mod.sendrequest
while True:
sendrequest(["issue-alarm", "homestead", "%d" % (ii,)])
runnings[ii] = True
threads = [Thread(target=foo, args=(ii,)) for ii in range(100)]
runnings = [False for thread in threads] …
```

[Reviewer: Ellie] Don't use the singleton Context - it's not multithread-safe

---

clearwater-infrastructure/usr/share/clearwater/bin/poll-sip

This changes our monit SIP polling to count a SIP 503 Service Unavailable response as a failed rather than successful poll, in line with our changes to Sprout which prioritize such polls during overload.

Overload Integration

---

clearwater-infrastructure/usr/share/clearwater/bin/clearwater-show-config

Alex,
When I merged the new clearwater-show-config / clearwater-check-config work, I dropped the `env -i` work.
My testing at the time suggested that it wasn't required, and that a sub shell was sufficient, but this has proved to be false, so I've added it back.

[Reviewer: Alex] Run in env -i as per the comment

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

This avoids using up too much space temporarily when copying logs into the diags dump. This is useful because if you have 1GB of free space, and 5GB of uncompressed logs that would compress down to 100MB, we are now able to capture those logs 😄 
I've tested this by spinning up a deployment with chef, running `cw-gather_diags` and checking the logs are correctly gathered. As a bonus, the `*_current.txt` symlinks now work in the diags dump 😃

Gather logs directory as a tar.gz

---

clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config

This change means that suggested parameters being missing no longer fail the validation for shared config.
I have live tested this by patching it onto a node and testing it works as expected. This was tested individually and alongside changes to https://github.com/Metaswitch/clearwater-etcd/pull/547

Allows a suggested parameter to be missing from shared_config and still pass the validation

---

cw_infrastructure/cw_infrastructure/check_config.py

This is to allow the worst error code to be returned rather than the newest, this was causing a bug when two options don't exist and the mandatory was before the warning level one.
I have live tested this a bit and it seems to avoid the previous issue.

Adjust check_config.py to return the highest value

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Hi Matt, could you please review this fix?
This is a simple enhancement to the diags for the 'ps' command. The issue was that the output of the original 'ps -eaf' command was not detailed enough (e.g. did not include memory information). I have replaced it with essentially 'ps aux' with more granularity in the timestamps. 
Here is a sample output from the clearwater-diag-monitor diags on an SPN node:
```
USER       PID %CPU %MEM   VSZ      RSS   TT   STAT  STARTED                             TIME       COMMAND
root         1      0.0      0.0        33480  2476  ?     Ss      Mon Sep 18 12:24:01 2017 00:00:01  /sbin/init
root         2      0.0      0.0        0          0        ?     S       Mon Sep 18 12:24:01 2017 00:00:00  [kthreadd]
```
(* sorry for the formatting, view under edit …

[Reviewer: MIRW] More detailed ps diagnostics

---

clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config

Hi Richard, 
Here is a fix to a change I believe you made earlier. Would you mind reviewing it?
Running the command "clearwater-check-config --show" now outputs the contents of the config files to the console AND checks the config for errors.
I have tested the fix by patching one of our l3-cc3 test boxes.

[Reviewer: RJW2] Fixed 'clearwater-check-config' command w.r.t. passing the '--show' option

---

cw_infrastructure/cw_infrastructure/clearwater_options.py

Adam,
As discussed this is a slight tweak to the change you just made to Clearwater validators.
If a deployment is not using Homestead Prov, it may have a configured Cassandra hostname, but that hostname isn't necessarily valid, and isn't required to be so.
As such, we disable checking the Cassandra hostname if Homestead Prov is not configured (i.e. `hs_provisioning_hostname` is not configured).

[Reviewer: Adam] Check if cassandra_hostname only if using HS-Prov

---

clearwater-infrastructure/PyZMQ/Makefile

Seb,
clearwater-infrastructure bundles a version of PyZMQ newer than is available on Ubuntu Trusty by default - specifically it bundles PyZMQ 16.02 (https://github.com/Metaswitch/clearwater-infrastructure/commit/39425a15c8908ef84a15076ca0659496126e0226) instead of 14.0.1 which is available in Ubuntu Trusty (see https://packages.ubuntu.com/trusty/python-zmq).
Currently we use setuptools to install this, but we do this in an odd way (installing it in the virtualenv, then reinstalling it in the virtualenv, then installing distribute, the installing buildout). Finally, we link the buildout installed in the venv into the bin folder (for extremely poorly defined reasons) and then run it via the symlink.
This is fairly horrible, and is causing spurious failures of the following form, which all …

[Reviewer: Seb] Use pip to install buildout instead of setuptools

---

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor

Hi Ellie, would you mind reviewing this please?
Here is another simple fix to the clearwater_diags_monitor. This fix add the following directories to the diags dump gathered by running cw-gather_diags.
-  ./monit_diags/root/var/lib/monit
-  .root/etc/netns
I tested the fix by running the command and checking for the relevant directories under the dump.
The monit-related script lives under clearwater-monit. Here is the related PR https://github.com/Metaswitch/clearwater-monit/pull/62.

[Reviewer: EM] Added directories to diags dump

---

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
clearwater-snmpd/usr/share/clearwater/infrastructure/scripts/snmpd_fd_handler

I've enhanced snmpd to expose file descriptor statistics from Clearwater MIBs. 
The bash script, snmpd_fd_handler, parses the request from SNMPD and works out which statistic is required before pulling the data off of proc and returning it. The definition of what each OID represents is in the MIB file that is part of a commit to clearwater-netsnmp-handlers.
The update to snmpd.conf ensures that we register the bash script for the relevant OIDs.
Testing has been live on an SPN. I haven't bothered with other node types.

[Reviewer: Richard] Expose file descriptor stats in Clearwater

---

debian/control

Mat,
bind9 is a DNS server, which binds to port 53. This conflicts with our configuration of dnsmasq, which means packages don't install correctly, which has been tripping up a user on the mailing list.
This change to our Debian control file forces bind9 to be uninstalled if clearwater-infrastructure is installed on a node.

[Reviewer: Mat] Prevent bind9 being installed alongside Clearwater

---

.gitignore
cw_infrastructure/cw_infrastructure/check_config_utilities.py
cw_infrastructure/cw_infrastructure/clearwater_options.py
cw_infrastructure/cw_infrastructure/test/validators_test.py
cw_infrastructure/cw_infrastructure/validators.py

Hi Richard,
Can you review this change to support INFORMs on non-standard ports. Change is in three parts:
- Add validator for lists of IP/domain with optional ports
- Modify snmp_ip to use the new validator
- Change the agent to parse out the ports where present (separate PR)
Testing
- Live testing with single and multiple IP addresses with ports specified
(completed before self-review - will do a final tyre kick after markups)
- UT with multiple 
Other thoughts:
- I've not mocked out the calls to the utils class like existing UTs have. That's because it feels more sensible to test the combined code here.
- I struggled to stick to the current naming convention because domain + ip addr + optional port was a lot of characters. Happy to have other suggestions.
- I've changed a UTILS.OK …

[Reviewer:Richard] Allow INFORMs to be sent to non-standard ports

---

clearwater-infrastructure/usr/share/clearwater/bin/sas_socket_factory.py
clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/sas_socket_factory

New sas_socket_factory script to interact with the new `sas.json` config file.
Writes the list of IP addresses present in `sas.jon` to either 
`/etc/clearwater-socket-factory/management.d/clearwater-infrastructure` 
or 
`/etc/clearwater-socket-factory/signaling.d/clearwater-infrastructure`  
depending on whether `sas_use_signaling_interface`  in `shared_config` is set to "Y".

[Reviewer: CJR] New socket factory script

---

cw_infrastructure/cw_infrastructure/check_config_utilities.py
cw_infrastructure/cw_infrastructure/validators.py

This is a part of the fix for: https://github.com/Metaswitch/clearwater-issues/issues/3691
2 things here:
1. As per the comment, we were setting a per-server timeout but not setting a lifetime on the DNS query, so it was actually taking 20s to fail if no DNS servers were responding. I've now set the lifetime to 4 (to allow at least 2 tries at 2s per try)
1. I've removed a duplicated function that wasn't used.
`make test` and `make verify` pass.

[Reviewer: Richard] Config validation dns timeout

---

cw_infrastructure/cw_infrastructure/clearwater_options.py

As we use sas.json to configure SAS, we no longer suggest that sas_server is set in shared config.
I've left sas_server present in configlint.py and I've left the validators in place as we use the value of the fiels in the migration process in: https://github.com/Metaswitch/clearwater-etcd-plugins/pull/61

Prevent warnings if sas_server is missing

---

clearwater-infrastructure/PyZMQ/Makefile

Seb,
This fixes a build issue with clearwater-infrastructure.
If the latest virtualenv is installed, when we create the virtualenv it will, by default have the latest version of setuptools (as the default has switched from not downloading from PyPI to downloading from PyPI).
If we have the latest version of setuptools (V39) it has commit https://github.com/pypa/setuptools/commit/eeeb9b27fa48fccf2b5d52919eff1c75c4ad1718. This commit breaks `zc.buildout`.
`zc.buildout` has a dependency on setuptools (unknown to me when I previously fixed this build in https://github.com/Metaswitch/clearwater-infrastructure/pull/537). I thought it didn't, because when I last changed this, I ran `pip freeze` to check what was is installed in the working venv. However, `pip freeze` doesn't list setuptools by …

[Reviewer: Seb] Pin setuptools to working version
