Metaswitch/clearwater-infrastructure

clearwater-memcached/usr/share/clearwater/bin/poll_memcached.sh
Add the standard "$namespace_prefix" when running netcat
=> [Reviewer Andy] Fix issue #123

clearwater-infrastructure/etc/monit/conf.d/node.monit
Matt, can you review this change to have an explicit check for the system
Fixes #139
=> [Reviewer: Matt] Add in specific system check

clearwater-infrastructure/usr/share/clearwater/bin/poll-http
This is the poll-http script for https://github.com/Metaswitch/chronos/pull/104
I'll also move poll_homestead/memento over to use this, and add a poll_sprout_http that uses it as well.
=> [Reviewer: Matt] Add poll-http script

clearwater-infrastructure/usr/bin/clearwater-upgrade, clearwater-memcached/usr/share/clearwater/infrastructure/scripts/memcached, debian/control
Update to memcached 1.6 (and related fixes)
=> Reviewer Matt - Memcached 1.6

clearwater-diags-monitor/usr/share/clearwater/clearwater-diags-monitor/conf/clearwater-diags-monitor.monit, clearwater-infrastructure/usr/share/clearwater/bin/poll-tcp, clearwater-memcached/usr/share/clearwater/bin/poll_memcached.sh, clearwater-memcached/usr/share/clearwater/infrastructure/conf/memcached_11211.monit, clearwater-snmpd/usr/share/clearwater/conf/snmpd.monit
memcached/snmpd changes (following template of https://github.com/Metaswitch/chronos/pull/107)
=> [Reviewer: Matt] Monit changes

debian/clearwater-memcached.postinst
Hi Matt,
Can you review this great fix I thought of for the clearwater-memcached.postinst script?
Thanks,
Graeme
=> Reviewer MIRW: Stop memcached rather than restarting it in postinst

Makefile, clearwater-auto-config/etc/clearwater/config, debian/.gitignore, debian/clearwater-auto-config-docker.init.d, debian/clearwater-auto-config-docker.install, debian/clearwater-auto-config-generic.init.d, debian/control, debian/rules
Andy,
Please can you review my changes to add a clearwater-auto-config-docker package?  The meat is in clearwater-auto-config.init.d - everything else is basically just boilerplate.
I've tested this live.
Matt
=> [Reviewer: Andy] Add clearwater-auto-config-docker package

clearwater-infrastructure/usr/share/clearwater/bin/generic_create_diameterconf
Matt, can you review this change to support adding the rt_ignore_dh extension to the diameter configuration file
=> [Reviewer: Matt] Sto1226

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
Small change to add in chronos handler
=> [Reviewer: Matt] Add in chronos stat handler

clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/migrate_shared_config
We should do a better fix, as discussed, but this makes things not broken for now.
=> [Reviewer: Andy] Comment out blank values

clearwater-diags-monitor/usr/share/clearwater/clearwater-diags-monitor/conf/clearwater-diags-monitor.monit, clearwater-memcached/usr/share/clearwater/infrastructure/conf/memcached_11211.monit, clearwater-snmpd/usr/share/clearwater/conf/snmpd.monit
Metaswitch/clearwater-monit#16
=> [No reviewer] Add in groups

clearwater-infrastructure/etc/monit/conf.d/ntp.monit
Adding an NTP monit file
Fixes #154
=> [Reviewer: Andy] Add ntp monit file

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
Minor updates to the clearwater-diags-monitor using 2.0.14
=> [Reviewer: Rob] Updates for cassandra 2.0.14

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
=> [Reviewer: Rob] Get cassandra and memcached info for memento

clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/configlint.py, clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/migrate_local_config, clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/switch_to_migrated_config
Fixes https://github.com/Metaswitch/clearwater-infrastructure/issues/174.
=> [Reviewer: Ellie] Fail on error

clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/switch_to_migrated_config, clearwater-memcached/usr/share/clearwater/bin/reload_memcached_users
Fixes parts 1 and 1 of https://github.com/Metaswitch/clearwater-etcd/issues/38.
=> [Reviewer: Ellie] Make scripts 'set -e' safe

clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/configlint.py, clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/migrate_local_config, clearwater-infrastructure/usr/share/clearwater/infrastructure/migration-utils/migrate_shared_config
Minor fixes to migrate scripts
=> [Reviewer: Andy] Migrate fixes

clearwater-auto-config/etc/clearwater/local_config, clearwater-auto-config/etc/clearwater/shared_config, debian/clearwater-auto-config-generic.init.d
This splits up the local/shared config files in auto configuration
=> [Reviewer: Andy] Split into local and shared config

debian/clearwater-auto-config-docker.init.d
Matt
Can you review.  I've tested both existing behaviour and also spinning up using the new ZONE parameter and appropriately programmed DNS entries.
Mike
=> [Reviewer Matt] Add support for DNS service discovery

debian/clearwater-auto-config-docker.init.d
Fix bug in fix for DNS service discovery that broke operation when DNS discovery not in use.
=> [No reviewer required] Remove extra white space on assignment

debian/clearwater-auto-config-docker.install, debian/clearwater-auto-config-generic.install
A real victory for testing!
I haven't verified this either yet but I'm intending to merge this in immediately because a) it'll make testing easier and b) master is broken anyway now so...
Feel free to review anyway!!
Graeme
=> Reviewer RKD: Also need is_ipv6_address.py

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
Must not be merged before https://github.com/Metaswitch/clearwater-snmp-handlers/pull/45.
=> [Reviewer: Ellie] Drop alarm_handler.so

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
=> [No reviewer] Sto1289 statistics

debian/clearwater-auto-config-docker.init.d
Andy
These are the changes to Docker auto configuration support required to support etcd running as a proxy using an external etcd cluster.  These obviously depend on the changes to clearwater-etcd for running as a proxy.  The code still supports the old way of running Docker links.  The new function is triggered by specifying the ETCD_PROXY variable on the docker run command.
I still need to submit a pull request for changes to the Dockerfiles and documentation in the clearwater-docker repo, but I can't test final versions of those until these changes are in the stable repos (at the moment my Dockerfiles have manual patches in them for testing these changes).
Mike
=> [Reviewer Andy] Change to docker auto configuration to support etcd proxy

clearwater-infrastructure/usr/share/clearwater/bin/run-in-signaling-namespace
=> [Reviewer: Rob] Add signaling namespace script

clearwater-infrastructure/usr/share/clearwater/bin/poll-tcp
I changed poll-tcp such that it is the caller's responsibility to run it in the right namespace.
=> [Reviewer: Rob] Fixes for etcd issue #110

debian/clearwater-infrastructure.postinst, debian/clearwater-infrastructure.prerm
=> [No reviewer] Check for bashrc file in home directory

debian/clearwater-auto-config-docker.init.d
Add quotes when testing with `-n`
Fixes #234
=> [No reviewer] Add quotes

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/sas_socket_factory
=> [No reviewer] Remove restart command

scripts/clearwater-aio-install.sh
=> [Reviewer: Ellie] Install clearwater-prov-tools alongside homestead-prov

debian/clearwater-auto-upgrade.init.d, debian/control
=> Reviewer AMC: Use clearwater-upgrade in clearwater-auto-upgrade

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
Andy,
Please can you review my fix to add an internal SNMP community, only accessible locally.
This is required for https://github.com/Metaswitch/chronos/issues/167.  I've tested live.
Matt
=> [Reviewer: Andy] Add clearwater-internal community

debian/clearwater-auto-config-docker.init.d
Ellie,
Please can you review this, which fixes #244?  Basically, we're just comma-separating the list.  I also replaced the superfluous `awk` with a `cut`.  I've tested live.
Thanks,
Matt
=> [Reviewer: Ellie] Support multiple DNS servers in clearwater-auto-config-docker

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
Rob,
Please can you review this, which fixes #248?
It's pretty trivial, and I've tested live.
Thanks,
Matt
=> [Reviewer: Rob] Use correct name of check_cluster_state tool when gathering diags bundle

debian/control
Depend on the specific `net-snmp` packages to pick up the fix for http://sourceforge.net/p/net-snmp/bugs/2669/.
=> Reviewer Rob - Use specific snmp version

scripts/clearwater-aio-install.sh
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=728775 for the underlying issue.
Tested live as part of cutting the release.
=> Reviewer Matt - Send /dev/null to apt-get commands

clearwater-diags-monitor.md, clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
=> [Reviewer: Matt] Get pidfiles in diags dumps

debian/clearwater-snmpd.postinst, debian/clearwater-snmpd.prerm
Matching fix to https://github.com/Metaswitch/clearwater-snmp-handlers/pull/99/files
=> [Reviewer: Matt] Use stop rather than restart

clearwater-infrastructure/usr/share/clearwater/bin/alarms.py
Partial fix to https://github.com/Metaswitch/clearwater-snmp-handlers/issues/91.
=> [Reviewer: Alex] Remove the alarms_enabled check

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
Proxying the subscription stats OID to the infinite table
=> proxy to subscription stats

clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_utils.py
Part of https://github.com/Metaswitch/clearwater-etcd/pull/223.
=> [No reviewer] Write files atomically, avoid corruption

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
Proxy code. 
Proxies blah .0 to infinite.tag.2.1
Only thing you might fuss about is line spacing. i thought it looked neat to separate the sections with a slightly larger gap, but not sure if this goes against coding standards.
=> [Reviewer: Andy] Proxies for chronos scalars

clearwater-infrastructure/usr/share/clearwater/bin/issue_alarm.py
Fixes https://github.com/Metaswitch/clearwater-etcd/issues/214
=> [Reviewer: Rob] iss214: Adds comment explaning alarm state->severity mapping

debian/clearwater-infrastructure.postinst, debian/clearwater-infrastructure.triggers, debian/clearwater-memcached.postinst, debian/clearwater-memcached.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
=> [No reviewer] Add alarm triggers

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
Rearrange entries, and add in BIND stats
=> [No Reviewer] SNMP proxy for new chronos stats

clearwater-infrastructure/usr/share/clearwater/bin/check-uptime, clearwater-memcached/usr/share/clearwater/infrastructure/conf/memcached_11211.monit
Here is the utility script used to check process uptime. This allows us to do so every 3 cycles.
=> [Reviewer Adam] Monit alarms

clearwater-memcached/usr/share/clearwater/clearwater-cluster-manager/plugins/memcached_plugin.py
Similar to https://github.com/Metaswitch/chronos/pull/236
=> [No reviewer] Set alarm at all stages in the clustering process

debian/clearwater-auto-config-docker.init.d
Counterpart to https://github.com/Metaswitch/clearwater-docker/pull/18.
=> [Reviewer: Matt] Move to the Docker Compose v2 API and Docker networks

clearwater-infrastructure/usr/share/clearwater/bin/ent_log.py
Switch to a less congested logging facility for ENT logs
=> [Reviewer AMC] Switch ENT logging channel to local7

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
Thought this would be useful while investigating https://github.com/Metaswitch/clearwater-etcd/issues/262, so I added it.
=> [Reviewer: Ellie] Add lsof output to diags

clearwater-diags-monitor/usr/share/clearwater/bin/clearwater_diags_monitor
This reverts commit c25793352a1990c297a3244ae26c831a5b5834fc.
@eleanor-merry reported problems, so let's just back it out. #gitrevert
=> Revert "Add lsof output to diags"

clearwater-auto-config/etc/clearwater/local_config
Fixes https://github.com/Metaswitch/sprout/issues/806.
=> [Reviewer: GDR] Only keep 50MB of logs on all-in-one nodes

clearwater-auto-config/etc/clearwater/shared_config, scripts/clearwater-aio-install.sh
Use the change in https://github.com/Metaswitch/clearwater-cassandra/pull/93.
=> [Reviewer: Matt] Expect clearwater-cassandra to control Cassandra's memory usage

debian/clearwater-auto-config-generic.init.d
I'll test by installing this package on an OVA, rebooting so the change is applied, and making a test call through it.
=> [Reviewer: Ellie] Ensure sprout_hostname really is a hostname, not an IP address

debian/clearwater-auto-config-docker.init.d
Part of https://github.com/Metaswitch/clearwater-docker/pull/19.
=> [Reviewer: Matt] Use an etcd proxy on all Docker nodes

README.md, debian/clearwater-radius-auth.postinst
Adds the radius authentication check to pam.d/login as well as pam.d/ssh (as this process is also whitelisted for pam authentication)
=> [Reviewer: Adam] Update pam.d/login as well as sshd

clearwater-infrastructure/usr/share/clearwater/bin/poll-tcp
=> [No reviewer] Add -z

debian/clearwater-socket-factory.service
Similar to https://github.com/Metaswitch/clearwater-monit/pull/34
=> [No Reviewer] Have process restart set to always, to cover when PID is killed

rpm/clearwater-snmpd.spec
Update to use new el7_2 versioned net-snmp
=> [No Reviewer] Update net-snmp dependencies

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/logging.bash
Hi Alex,
We thought it would be useful to have a common logging facility for Bash since Bash logging is something we could improve on in Clearwater Core :dromedary_camel:. I couldn't find anything similar in the existing codebase, so thought I'd try to write a very basic script that we could start to use across our scripts.
Do you think this is something that would be useful for PC?
If so, would you mind reviewing the current code to see if there's any problems/extensions that would be helpful? 
Also, if there's a better place for me to put this then let me know :turtle:
=> [Reviewer: Alex] Add bash logging library

rpm/clearwater-diags-monitor.spec
Same reasoning as https://github.com/Metaswitch/clearwater-infrastructure/pull/360
=> [No reviewer] Fix centos dependencies as well

clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/1hosts
=> [No reviewer] Further markups

scripts/clearwater-aio-install.sh
=> [Reviewer: AJL] Use split-storage package names on AIO node

clearwater-diags-monitor/usr/share/clearwater/bin/gather_diags_and_report_location, clearwater-diags-monitor/usr/share/clearwater/infrastructure/install/clearwater-diags-monitor.postinst
Unlike #378, I have tested this one...
=> [Reviewer: Ellie] Remove other reference to /home/clearwater

clearwater-snmpd/usr/share/clearwater/infrastructure/install/clearwater-snmpd.postinst
=> No reviewer: Don't delete alarms unix domain socket

clearwater-infrastructure/usr/share/clearwater/bin/reload_dns_config
Just runs all scripts in
/usr/share/clearwater/infrastructure/scripts/reload/dns_config/
=> [Reviewer: Ellie] Add reload_dns_config script

CHANGELOG.md, README.md
CHANGELOG.md has been left untouched through three years of changes - shall we remove it?
=> [Reviewer: RKD] Remove unused changelog and readme reference to it

debian/clearwater-infrastructure.links, rpm/clearwater-infrastructure.spec
Companion PR to https://github.com/Metaswitch/clearwater-etcd/pull/355
=> [Reviewer EM] Add /usr/bin links to commonly used scripts

clearwater-radius-auth/etc/libnss-ato.conf, clearwater-radius-auth/etc/libnss-ato.conf.TEMPLATE
Moved the config across to a template and added a comment explaining it all
=> [Reviewer: Ellie] Move config to template, to avoid user change conflicts

clearwater-snmpd/etc/snmp/snmpd.conf.clearwater-snmpd
Don't log successful connections in syslog
=> [No reviewer] Turn off spammy logs

debian/clearwater-infrastructure.links
=> [No reviewer] Make shortcut consistent

clearwater-socket-factory.md
Just adding some documentation changes that were missed off the clearwater-socket-factory.md #337 was merged.
=> [Reviewer: Richard] Socket factory readme

Makefile
This fixes up the centos build
=> [Reviewer: Rob] Don't build vellum and dime for centos

clearwater-infrastructure/usr/share/clearwater/bin/reload_dns_json
Rename /etc/clearwater/dns_config to /etc/clearwater/dns.json
=> [No reviewer] Update filename

debian/clearwater-infrastructure.links
=> [Reviewer: Sathiyan] Create clearwater-infrastructure.links

clearwater-infrastructure/usr/share/clearwater/bin/restart_node_processes, debian/clearwater-infrastructure.links
This script restarts all processes on a node that use local_config/shared_config/user_settings
=> [Reviewer: Sathiyan] Add a simple restart script

clearwater-memcached/usr/share/clearwater/infrastructure/conf/memcached_11211.monit, clearwater-snmpd/usr/share/clearwater/conf/snmpd.monit
As per https://github.com/Metaswitch/sprout/pull/1863
=> [No reviewer] Don't wait for 6 cycles before killing a process

clearwater-infrastructure/etc/dnsmasq.d/dnsmasq.clearwater.conf
I made a stupid.
On the upside, we spotted that we have no monitoring of the health of dnsmasq.
=> [No reviewer] Fix dnsmasq config file

clearwater-infrastructure/usr/share/clearwater/bin/run-in-signaling-namespace
=> [Reviewer: Alex] Use $@ rather than $*

debian/control
Seb,
This bumps the version number and adds the memcached debug packages from https://github.com/Metaswitch/memcached/pull/22
=> [Reviewer: Seb] Add memcached debug packages

debian/clearwater-memcached.install
linked with https://github.com/Metaswitch/clearwater-etcd/pull/501
=> [No Reviewer] Remove removed plugin

debian/clearwater-auto-config-docker.init.d
Enhance Docker auto-configuration to accept an HSS env variable that causes the deployment to be set up to reference an HSS instead of using homestead-prov.
=> Add support for external HSS

debian/clearwater-infrastructure.links
=> Md6 add link

debian/control
Fallout from https://github.com/Metaswitch/astaire/pull/93
=> [Reviewer: Seb] Add rogers to vellum nodes

clearwater-infrastructure/usr/share/clearwater/bin/clearwater-check-config
Use correct string comparison operator
=> [Reviewer: Adam] Use correct string comparison operator

debian/clearwater-infrastructure.links
This reorders sbin and bin links
=> Reorders list of links and puts a line between sbin and bin

clearwater-infrastructure/usr/share/clearwater/infrastructure/bin/set_log_level
=> Don't create user_settings in current directory

debian/clearwater-infrastructure.links
This has been changed to move show-config links
=> Updates links to avoid merge conflicts

cw_infrastructure/cw_infrastructure/check_config.py, cw_infrastructure/cw_infrastructure/check_config_utilities.py
Ken can you just check this, it should be really trivial...
I won't put this into v11.1
=> Updates error text for a warning if a option is suggested

Makefile, cw_infrastructure/Makefile, debian/clearwater-infrastructure.install
See https://github.com/Metaswitch/clearwater-build-infra/pull/76
=> [No reviewer] Updates for changes to python build infra

cw_infrastructure/cw_infrastructure/clearwater_options.py, cw_infrastructure/cw_infrastructure/validators.py
Hi Richard, would you mind reviewing this PR please?
This PR enhances the validation of Clearwater config as well as introduces some minor fixes. The affected areas are:
- Enhance the validation of DNS entries making sure they are not just syntactically correct, but also resolvable with the current DNS configuration.
-  Fix typos in one of the existing functions - resolvable_ip_or_domain_name_list_validator.
=> [Reviewer: RJW2] Clearwater config DNS checks

clearwater-infrastructure/usr/share/clearwater/bin/sas_socket_factory.py, clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/sas_socket_factory
Revert the revert.
Updates the sas_socket_factory, for the new sas.json file.  This code was merged in hastily originally, hence the rather confusing workflow
=> Revert "Revert "[Reviewer: CJR] New socket factory script""
